name: Tag the repo
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tag release value'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
permissions:
  actions: write
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  build:
    name: Create Tags Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ inputs.tag_name }}
          tag_exists_error: false
          message: "Merging x into y for ${{ inputs.tag_name }}"

      - name: Create Tag named release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "release"
          force_push_tag: true
          message: "Merging for a tag named release"
          run: echo running on branch ${GITHUB_REF##*/}  
           
