# This is a basic workflow that is manually triggered

name: Repository Merge and Tag

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Repository URL"
        type: choice
        # Default value if no value is explicitly provided
        default: "adamteller/samples.git"
        options: ["git@github.com:adamteller/samples.git", "git@github.com:adamteller/BDD.git"]
        required: true
      source_branch:
        description: "Code is from?"
        default: "develop"
        type: string
        required: true 
      dest_branch:
        description: "Code going to?"
        default: "main"
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
      
      - name: Merge ${{ inputs.source_branch }} -> ${{ inputs.dest_branch }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.source_branch }}
          target_branch: ${{ inputs.dest_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.repo_url }}


