# This is a basic workflow that is manually triggered

name: Repository Merge and Tag

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Repository URL"
        type: choice
        # Default value if no value is explicitly provided
        default: "git@github.com:adamteller/samples.git"
        options: ["git@github.com:adamteller/samples.git", "git@github.com:adamteller/BDD.git"]
        required: true
      source_branch:
        description: "Code is from?"
        default: "develop"
        type: string
        required: true 
      dest_branch:
        description: "Code going to?"
        default: "main"
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: State Intent
      run: | 
        echo "Merge ${{ inputs.source_branch }} into ${{ inputs.dest_branch }} in repo: ${{ inputs.repo_url }}"

